Import('RTT_ROOT')
Import('rtconfig')
from building import *

# get current directory
cwd = GetCurrentDir()

src	= Glob('src/*.c')
CPPPATH = [cwd + '/inc', str(Dir('#'))]

CPPDEFINES = ['DEBUG']
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')