from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('er-rest-example/*.c')
src    += Glob('ipv6/6lbr/*.c')
src    += Glob('ipv6/slip-radio/*.c')

path    = []

group = DefineGroup('Contiki', src, depend = [''], CPPPATH = path)

Return('group')
