from building import *
Import('rtconfig')

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('*.c')

path    = [cwd]

if rtconfig.PLATFORM == 'gcc':
	LIBS = ['radio_si446x_0.1.1_armcm4_gcc']
elif rtconfig.PLATFORM == 'iar':
	LIBS = ['libradio_si446x_0.1.1_armcm4_iar']
elif rtconfig.PLATFORM == 'armcc':
	LIBS = ['radio_si446x_0.1.1_armcm4_keil']

LIBPATH = [cwd + '/radio']

group = DefineGroup('Contiki', src, depend = [''], CPPPATH = path, LIBS = LIBS, LIBPATH = LIBPATH)

Return('group')
