from building import *
Import('rtconfig')

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('*.c')

path    = [cwd]

if rtconfig.PLATFORM == 'iar':
	LIBS = Glob('radio/*_iar.a')
elif rtconfig.PLATFORM == 'gcc':
	LIBS = Glob('radio/*_gcc.a')
elif rtconfig.PLATFORM == 'armcc':
	LIBS = Glob('radio/*_armcc.a')

LIBPATH = [cwd + '/radio']

group = DefineGroup('Contiki', src, depend = [''], CPPPATH = path, LIBS = LIBS, LIBPATH = LIBPATH)

Return('group')
